image: amazonlinux:latest
definitions:
   steps:
    - step: &build-test
        name: Build and test
        script:
          - yum update
          - dnf install -y findutils
          - yum install git -y
          - bash script.sh
        artifacts:
          - myfiles/**  

    - step: &deployment
        name: Deployment to ec2 
        script: 
          - echo "Deploying to production environment"
          - ls -l
          - pipe: atlassian/scp-deploy:1.3.0
            variables:
                USER: '${USER}'
                SERVER: '${SERVER}'
                REMOTE_PATH: '/var/www/html/esigned-html/'
                LOCAL_PATH: 'myfiles/*'
                

          - pipe: atlassian/ssh-run:0.5.0
            variables:
              SSH_USER: '${USER}'
              SERVER: '${SERVER}'
              COMMAND: 'sudo systemctl restart httpd' 
              

        

pipelines:
  default:
    - step: *build-test
    - step: 
        <<: *deployment
        deployment: Production

          